### ISSUE TITLE
Bugtracker

### ISSUE THREAD

**Issue by Smolnikovp** [volchata/pepo_client#18]
<strike>1. tweet.bemhtml.js - убрать у кнопки mods: { homescreen: true }, которая приводит к неверному отображению кнопок действий в блоке tweet</strike>
2. ленту -> в отдельный блок с margin-top и  bottom, чтобы не перекрывалась менюшками
<strike>3. position: fixed - не работает на мобильных устройствах android < 4.3, iOS < 8.</strike> 
<strike>4. Переделать нижнее меню с control-group на radio-group, по причине первоначально неправильного выбора блока для реализации.</strike>

**Comment by Klimanso** [comment]
Вот нашел таки issue. xD
А вот я не верю в то, что нужно удалять mods: { homescreen: true }! В багах пишется, что работает не так, чтобы все понимали, что да - это бага.
Вот второй пункт более похож на описание бага.

**Comment by Klimanso** [comment]
Если изменения больше технические и не являются явными багами в интерфейсе, нужно попытаться тоже максимально точно описать для чего они, фундаментом для чего могут стать, какой профит, какую дырку в архитектуре лечат ну и т.п.
