### ISSUE TITLE
Верстка: нижнее меню для профиля

### ISSUE THREAD

**Issue by dustyo-O** [volchata/pepo_client#46]
Нижнее меню для всех задач, связанных с профилем, #6 #7 #8. 
Кнопку "Не сейчас" переделываем в "Отмена".

https://cloud.githubusercontent.com/assets/14638147/17662638/fb0efd7e-62f7-11e6-9bd1-1fdbdd5c6d8b.PNG
https://cloud.githubusercontent.com/assets/14638147/17662596/93b95390-62f7-11e6-953d-1238b1a68ade.PNG

**Comment by Smolnikovp** [comment]
Есть `mods: { accept: true }` для нижнего меню - там сделано уже.
